const chai = require('chai')
const chaiHttp = require('chai-http')
const should = chai.should()
const request = require('supertest')
chai.use(chaiHttp)
// tests for app
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('app', '/server.js', 'handler');

describe('app', () => {
  before((done) => {
    done();
  });
  const server = request('http://localhost:3000/api')
  it('chai first test', (done)=>{
    try{
      server.get('/').end((err,res)=>{
        res.should.have.status(200)
        res.should.have.property('body')
        res.body.should.have.property('msg')
        res.body.should.have.property('error')
        res.body.error.should.equal(false)
        res.body.msg.should.contain('Success Ok. HOME PAGE.')
        done()
      })
    }catch(ex){
      console.log('ERROR', ex)
      done()
    }
    
  })

  it('chai second test', (done)=>{
    try{
        server.get('/index').end((err,res)=>{
        res.should.have.status(200)
        res.should.have.property('body')
        res.body.should.have.property('msg')
        res.body.should.have.property('error')
        res.body.error.should.equal(false)
        res.body.msg.should.contain('Success Ok. INDEX PAGE.')
        done()
      })
    }catch(ex){
      console.log('ERROR', ex)
      done()
    }
    
  })

  // it('First Test', () => {
  //   return wrapped.run({}).then((response) => {
  //     expect(response.statusCode).to.be.equal(200);
  //     expect(response).to.not.be.empty;
  //     const res = JSON.parse(response.body)
  //     console.log('RESPONSE: ',res)
  //     expect(response.body).to.not.be.empty;
  //     expect(res).to.have.property('msg')
  //     expect(res).to.have.property('error')
  //     expect(res.error).to.equal(false)
  //     expect(res.msg).to.contain('Success Ok. HOME PAGE.')
  //   });
  // });
});
