sudo: true
dist: xenial

language: node_js
node_js: 
  - node
go: 
  - 1.11.x


branches: 
  only: 
    - master

install: 
  - npm i 

before_script:
  - bash startOffline.sh
  - go run main.go test failing
  
script:
  - bash stopOffline.sh
  - echo "SUCCESS"

after_success:
  - echo "Deploying"
  - sls deploy

notifications: 
  email: true
  slack:
    rooms: 
      - opscaleindia:PBF4tVV10a56K6rZpKMVs95E
    on_success: always # default always
    on_failure: always # default always