language: node_js
node_js: 
  - node
# sudo: true
branches: 
  only: 
    - master

install: 
  - npm i 

before_script: 
  - sls invoke test

script:
  - echo "Test Passed"

after_success:
  - echo "SUCCESS"
  - sls deploy

notifications: 
 slack:
  rooms: 
    - opscaleindia:PBF4tVV10a56K6rZpKMVs95E
  on_success: always # default always
  on_failure: always # default always