language: node_js
node_js: 
  - node
# sudo: true
branches: 
  only: 
    - master
before_script: 
  - npm i 

script: 
  - echo "SUCCESS"

after_success:
  - sls deploy

notifications: 
 slack:
  rooms: 
    - opscaleindia:PBF4tVV10a56K6rZpKMVs95E
  on_success: always # default always
  on_failure: always # default always