service: express-application

provider: 
  name: aws
  runtime: nodejs8.10
  region: ap-south-1

plugins:
  - serverless-offline
  - serverless-mocha-plugin
# custom:
#   serverless-mocha-plugin:
    # preTestCommands: 
    #   - bash startOffline.sh
    # postTestCommands:
    #   - bash stopOffline.sh

functions: 
  app: 
    handler: server.handler
    events: 
      - http: 
          path: /api
          method: get
      # - http: 
      #     path: /api/index
      #     method: get
      - http:
          path: /api/{proxy+}
          method: get